import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NextAuthProvider from "@/provider/NextAuthProvider";
import Sidebar from "../Sidebar/page";




const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" flex gap-4">
      
          <NextAuthProvider>
          <Sidebar/>
            
            {children}
            
          
          </NextAuthProvider>
        
      </body>
    </html>
  );
}
